### PR TITLE
Fix dependencies.

### PR DESCRIPTION
**Pull request by DFurnes**
This pull request fixes builds so we can get things deployed and working on production.

It seems like the lockfile got corrupted at this commit: 16f57bfd3ad5465d8f0a8917afb4c97d81ad1c5c

### CODE REVIEW

**Comment by DFurnes** [comment]
I also updated the Wercker config so it will only deploy to GitHub pages on the `master` branch, otherwise all pull requests were automatically going to production on each build.

**Review by chloealee — APPROVED** [review]
thank you @DFurnes !!

**Comment by DFurnes** [comment]
I've also enabled the "Report to SCM" checkbox on the build pipeline so we get build status on PRs.

**Comment by DFurnes** [comment]
No prob! Glad it was a quick fix. 😄

**Pull request merged**
